
platform :ios, '10.0'

inhibit_all_warnings!

target 'GoHaier' do
 pod 'BlocksKit'
 pod 'Masonry'
 pod 'AFNetworking'
 pod 'Toast', '~> 4.0.0'
 pod 'YYCache'
 pod 'AMapLocation-NO-IDFA'
 
 #下面是友盟的统计sdk
 pod 'UMCCommon'
 pod 'UMCSecurityPlugins'
 pod 'UMCCommon'
 pod 'UMCSecurityPlugins'
 pod 'UMCAnalytics'
 pod 'BuglyHotfix'


end

